# Generated by Django 4.0 on 2022-03-24 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settingsapp', '0001_initial'),
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('tr_date', models.CharField(max_length=30)),
                ('tr_additional_tax', models.IntegerField(default=0)),
                ('tr_additional_discount', models.IntegerField(default=0)),
                ('tr_grand_total', models.BigIntegerField()),
                ('tr_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('tr_shipping_charges', models.IntegerField(default=0)),
                ('tr_status', models.CharField(choices=[('Sent', 'sent'), ('Completed', 'completed'), ('Pending', 'pending')], default='Pending', max_length=15, verbose_name='tr_status')),
                ('tr_notes', models.TextField()),
                ('tr_total_product', models.IntegerField(default=0)),
                ('tr_from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_warehouse', to='settingsapp.warehouse')),
                ('tr_to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_to_warehouse', to='settingsapp.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('tr_product_cost', models.IntegerField()),
                ('tr_product_stock', models.IntegerField()),
                ('tr_product_quantity', models.IntegerField()),
                ('tr_product_discount', models.IntegerField()),
                ('tr_product_tax', models.IntegerField()),
                ('tr_sub', models.IntegerField()),
                ('tr_product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_product', to='productapp.product')),
                ('tr_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr', to='transfer_app.transfer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
