# Generated by Django 4.0 on 2022-03-24 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settingsapp', '0001_initial'),
        ('people', '0001_initial'),
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('sr_date', models.CharField(max_length=30)),
                ('sr_additional_tax', models.IntegerField(default=0)),
                ('sr_additional_discount', models.IntegerField(default=0)),
                ('sr_paid', models.BigIntegerField(default=0)),
                ('sr_due', models.BigIntegerField(default=0)),
                ('sr_grand_total', models.BigIntegerField()),
                ('sr_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('sr_shipping_charges', models.IntegerField(default=0)),
                ('sr_status', models.CharField(choices=[('Ordered', 'ordered'), ('Completed', 'completed'), ('Pending', 'pending')], default='Pending', max_length=15, verbose_name='sr_status')),
                ('sr_payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'partial'), ('Unpaid', 'unpaid')], default='Unpaid', max_length=15, verbose_name='sr_payment_status')),
                ('sr_notes', models.TextField()),
                ('sr_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_customer', to='people.customer')),
                ('sr_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_warehouse', to='settingsapp.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sales_return_payment_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('sr_payment_date', models.CharField(blank=True, max_length=50, null=True)),
                ('sr_payment_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('sr_payment_choice', models.CharField(blank=True, max_length=50, null=True)),
                ('sr_payment_amount', models.BigIntegerField(default=0)),
                ('sr_payment_due', models.BigIntegerField(default=0)),
                ('sr_payment_note', models.TextField()),
                ('sr_payment_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_payment_sales', to='sales_return.sales_return')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sales_return_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('sr_product_cost', models.IntegerField()),
                ('sr_product_stock', models.IntegerField()),
                ('sr_product_quantity', models.IntegerField()),
                ('sr_product_discount', models.IntegerField()),
                ('sr_product_tax', models.IntegerField()),
                ('sr_sub', models.IntegerField()),
                ('sr_product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_product', to='productapp.product')),
                ('sr_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_sales', to='sales_return.sales_return')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
