# Generated by Django 4.0 on 2022-03-24 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settingsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('expenses_category_name', models.CharField(blank=True, max_length=50)),
                ('expenses_description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('expenses_reference', models.CharField(blank=True, max_length=100)),
                ('expenses_date', models.CharField(max_length=50)),
                ('expenses_detail', models.TextField()),
                ('expenses_amount', models.BigIntegerField()),
                ('expenses_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_Warehouse', to='settingsapp.warehouse')),
                ('expensescategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp_category', to='expensesapp.expenses_category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
