# Generated by Django 4.0 on 2022-03-24 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productapp', '0001_initial'),
        ('people', '0001_initial'),
        ('settingsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases_return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('purchases_return_additional_discount', models.IntegerField(default=0)),
                ('purchases_return_date', models.CharField(max_length=30)),
                ('purchases_return_additional_tax', models.IntegerField(default=0)),
                ('purchases_return_grand_total', models.BigIntegerField()),
                ('purchases_return_notes', models.TextField()),
                ('purchases_return_shipping_charges', models.IntegerField(default=0)),
                ('purchases_return_status', models.CharField(choices=[('Completed', 'completed'), ('Pending', 'pending')], max_length=50, verbose_name='status')),
                ('purchases_return_paid', models.BigIntegerField(default=0)),
                ('purchases_return_due', models.BigIntegerField(default=0)),
                ('purchases_return_payment_status', models.CharField(choices=[('Paid', 'paid'), ('Partial', 'partial'), ('Unpaid', 'unpaid')], default='Unpaid', max_length=50, verbose_name='purchases_return_payment_status')),
                ('purchases_return_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('purchases_return_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_return_supplier', to='people.supplier')),
                ('purchases_return_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_return_warehouse', to='settingsapp.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchases_return_purchase_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('purchases_return_product_cost', models.IntegerField()),
                ('purchases_return_produt_stock', models.IntegerField()),
                ('purchases_return_product_quantity', models.IntegerField()),
                ('purchases_return_product_discount', models.IntegerField()),
                ('purchases_return_product_tax', models.IntegerField()),
                ('purchases_return_sub', models.IntegerField()),
                ('purchases_return_product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_return_product', to='productapp.product')),
                ('purchases_return_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_return_purchase', to='purchases_return.purchases_return')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='payment_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('pr_payment_date', models.CharField(blank=True, max_length=50, null=True)),
                ('pr_payment_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('pr_payment_choice', models.CharField(blank=True, max_length=50, null=True)),
                ('pr_payment_amount', models.BigIntegerField(default=0)),
                ('pr_payment_due', models.BigIntegerField(default=0)),
                ('pr_payment_note', models.TextField()),
                ('pr_payment_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_purchase_return', to='purchases_return.purchases_return')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
