# Generated by Django 4.0 on 2022-03-24 09:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_email', models.EmailField(max_length=120)),
                ('customer_phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='customer_phone_no')),
                ('customer_country', models.CharField(max_length=110)),
                ('customer_city', models.CharField(max_length=210)),
                ('customer_address', models.CharField(max_length=220)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('supplier_name', models.CharField(max_length=120)),
                ('supplier_email', models.EmailField(max_length=120)),
                ('supplier_phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='supplier_phone_no')),
                ('supplier_country', models.CharField(max_length=120)),
                ('supplier_city', models.CharField(max_length=120)),
                ('supplier_address', models.CharField(max_length=220)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
