# Generated by Django 4.0 on 2022-03-24 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0001_initial'),
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='settingsapp.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='settingsapp.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_unit', to='settingsapp.unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_unit', to='settingsapp.unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sale_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sale_unit', to='settingsapp.unit'),
            preserve_default=False,
        ),
    ]
