# Generated by Django 4.0 on 2022-03-24 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('settingsapp', '0001_initial'),
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('sales_date', models.CharField(max_length=30)),
                ('sales_additional_tax', models.IntegerField(default=0)),
                ('sales_additional_discount', models.IntegerField(default=0)),
                ('sales_paid', models.BigIntegerField(default=0)),
                ('sales_due', models.BigIntegerField(default=0)),
                ('sales_grand_total', models.BigIntegerField()),
                ('sales_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('sales_shipping_charges', models.IntegerField(default=0)),
                ('sales_status', models.CharField(choices=[('ORDERED', 'ordered'), ('COMPLETED', 'completed'), ('PENDING', 'pending')], default='PENDING', max_length=15, verbose_name='sales_status')),
                ('sales_payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'partial'), ('Unpaid', 'unpaid')], default='Unpaid', max_length=15, verbose_name='sales_payment_status')),
                ('sales_notes', models.TextField()),
                ('sales_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_Customer', to='people.customer')),
                ('sales_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_Warehouse', to='settingsapp.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sales_payment_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('sales_payment_date', models.CharField(blank=True, max_length=50, null=True)),
                ('sales_payment_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('sales_payment_choice', models.CharField(blank=True, max_length=50, null=True)),
                ('sales_payment_amount', models.BigIntegerField(default=0)),
                ('sales_payment_due', models.BigIntegerField(default=0)),
                ('sales_payment_note', models.TextField()),
                ('sales_payment_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sales', to='salesapp.sales')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sales_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('sales_product_cost', models.IntegerField()),
                ('sales_product_stock', models.IntegerField()),
                ('sales_product_quantity', models.IntegerField()),
                ('sales_product_discount', models.IntegerField()),
                ('sales_product_tax', models.IntegerField()),
                ('sales_sub', models.IntegerField()),
                ('sales_product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_Product', to='productapp.product')),
                ('sales_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_sales', to='salesapp.sales')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
