# Generated by Django 4.0 on 2022-03-24 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settingsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('adj_date', models.CharField(max_length=40)),
                ('adj_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('adj_note', models.TextField()),
                ('adj_total_product', models.IntegerField(default=0)),
                ('adj_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_warehouse', to='settingsapp.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Adjustment_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('adj_product_code', models.BigIntegerField()),
                ('adj_product_name', models.CharField(max_length=100)),
                ('adj_stock', models.BigIntegerField(default=0)),
                ('adj_quantity', models.BigIntegerField(default=0)),
                ('adj_type', models.CharField(choices=[('Addition', 'addition'), ('Subtraction', 'subtraction')], default='Addition', max_length=15, verbose_name='adj_type')),
                ('adj_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adj_detail', to='adjustment_app.adjustment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
