# Generated by Django 4.0 on 2022-03-24 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('brand_name', models.CharField(max_length=120)),
                ('brand_description', models.CharField(max_length=220)),
                ('brand_image', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('category_code', models.IntegerField()),
                ('category_name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('unit_name', models.CharField(max_length=210)),
                ('short_name', models.CharField(max_length=120)),
                ('base_unit', models.CharField(blank=True, max_length=120)),
                ('operator', models.CharField(blank=True, max_length=10)),
                ('operation_value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('warehouse_name', models.CharField(max_length=120)),
                ('warehouse_phone', models.CharField(max_length=120)),
                ('warehouse_country', models.CharField(max_length=120)),
                ('warehouse_city', models.CharField(max_length=120)),
                ('warehouse_email', models.EmailField(max_length=220)),
                ('warehouse_zipcode', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('product_cost', models.BigIntegerField(default=0)),
                ('stock', models.BigIntegerField(default=0)),
                ('qty', models.BigIntegerField(default=0)),
                ('discount', models.BigIntegerField(default=0)),
                ('tax', models.BigIntegerField(default=0)),
                ('subtotal', models.BigIntegerField(default=0)),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prd_war', to='productapp.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouseid', to='settingsapp.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
